version: '3'

services:
  app:
    extends:
      file: ../docker/basic-nodejs-app/docker-compose.yml
      service: app
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
    depends_on:
      - app 
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
