version: '3'

services:
  app:
    extends:
      file: ../docker/basic-nodejs-app/docker-compose.yml
      service: app
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
  k6:
    image: grafana/k6
    volumes:
      - ./:/tmp
    ports:
      - "6565:6565"
    command: run --vus 1000 --duration 20s /tmp/script.js --out influxdb=http://influxdb:8086/k6
    depends_on:
      - app
      - influxdb
