version: '3'

services:
  app:
    image: node:14
    command: bash -c "yarn && yarn start"
    restart: unless-stopped
    volumes:
    - '.:/usr/src/app'
    working_dir: /usr/src/app
    ports:
      - '3300:3300'
