version: '3.9'

services:
  app:
    extends:
      file: ../docker/basic-nodejs-app/docker-compose.yml
      service: app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3300" ]
      interval: 5s
      timeout: 10s
      retries: 3
  wrk:
    build: .
    command: -t 4 -c 5 -d 10s --latency http://app:3300
    depends_on:
      app:
        condition: service_healthy
